action: ??? # train or test
name: ???
modality: "RGB"
total_batch: 128
batch_size: 64
gpus: null
resume_from: null
logname: null
models_dir: null
validation_function: trimmed_validation
boundaries_supervision: True
SBL_k: null
DBL_threshold: null
delta: 20
ABD: null
resume_name: null
feat_dir: null

# Hierarchical configuration (paths relative to configs/)
extends: null

# Mixed precision training (disabled by default)
amp: False

train:
  full_length: False
  detached_clips: True
  num_iter: 1500
  lr_steps: 2000
  eval_freq: 50
  start_test_iter: 1000
  num_clips: 4
  dense_sampling:
    RGB: True
    Flow: True
  num_frames_per_clip:
    RGB: 8
    Flow: 8

test:
  full_length: True
  detached_clips: False
  untrimmed: False
  num_clips: 1
  dense_sampling:
    RGB: True
    Flow: True
  num_frames_per_clip:
    RGB: 1
    Flow: 1

dataset:
  annotations_path: train_val
  shift: ???
  prefetch: 4
  workers: 16
  RGB:
    stride: 2
    data_path: null
    tmpl: "img_{:010d}.jpg"
    channels: 3
  Flow:
    stride: 1
    data_path: null
    bg_path: null
    tmpl: "{:s}_{:010d}.jpg" # "x_0000000042.jpg" or "y_0000000042.jpg"
    channels: 2
  Event:
    rgb4e: 6
    channels: 6

# these are the action recognition models for each modality
models:
  model: Movinet
  causal: True
  version: a0
  pretrained: True
  dropout: 0.2
  normalize: True
  resolution: 172
  kwargs: { }
  lr: 0.01
  sgd_momentum: 0.9
  weight_decay: 1e-7
  batch_norm_layers: 1
  batch_norm_affine: True
  bn_momentum: 0.1
